default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: 12345

development:
  <<: *default
  database: data

test:
  <<: *default
  database: data

production:
  <<: *default
  database: data
  username: postgres
  password: root